repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['baseline', '.secrets.baseline']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.2
    hooks:
      # Run the linter.
      - id: ruff
        types: [python]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types: [python]