services:
  app:
    build:
      context: ../..
      dockerfile: deployment/local/Dockerfile
      args:
        BUILD_PATH: "deployment/local"
        IMAGE: "python"
        TAG: "3.12.4-slim-bullseye"
        USER_NAME: "bg_rank"
        USER_ID: "1200"
        AWS_CREDENTIALS_PATH: "/tmp/credentials"
        DJANGO_SETTINGS_PATH: "/tmp/django_settings"
    container_name: bg_rank
    volumes:
      - ../..:/workspace
    