# Generated by Django 5.2.1 on 2025-06-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_match_end_at_alter_match_season_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchpalyer",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
