# Generated by Django 5.2.1 on 2025-06-10 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_rename_matchpalyer_matchplayer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="enroled_players",
            new_name="enrolled_players",
        ),
        migrations.CreateModel(
            name="SeasonPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.season",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="season",
            name="enrolled_players",
            field=models.ManyToManyField(
                through="dashboard.SeasonPlayer", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "season"), name="unique_season_player"
            ),
        ),
    ]
